version: '3'

services: 
    db:
        image: postgres
        restart: always
        env_file: 
            - db.env
        ports: 
            - "5432:5432"
        volumes: 
            - ./db:/var/lib/postgresql/data/

    # backend:
    # frontend: